### ISSUE TITLE
Harware back button on android closes the app on the last tab. 

### ISSUE THREAD

**Issue by Yasir5247** [kanzitelli/rnn-starter#104]
image i had three tabs in my app.

Tab1 -> Tab2 -> Tab3

on Tab3 if i press hardware button on android it directly closes the app like this

close <- Tab3(press)

here is how i feel it should be when the user press hardware back button on Tab3

close <-Tab1 <- Tab2 <- Tab3(press)

possible solutions according to i know:
-----------------------------------------
On Tab3 if the user press the hardware back button. switch to Tab2 programatically and on Tab2 switch to Tab1 ...close.
Is there any automatic way to achieve this through some configuration that i' don't know of. :)

**Comment by kanzitelli** [comment]
This issue is not related to the starter. It's behaviour of RNN how it is. The only solution that comes to my mind is to subscribe to tab presses, save the history and on hardware back button press navigate back according to the stack. This kind of behaviour is automatically achieved in react-navigation as it uses different approach.
