### ISSUE TITLE
help needed: Convert uni-modules to expo-modules

### ISSUE THREAD

**Issue by julianklumpers** [kanzitelli/rnn-starter#57]
Looks like Expo has deprecated uni-modules: [https://docs.expo.dev/bare/installing-unimodules/](https://docs.expo.dev/bare/installing-unimodules/)
And switched to expo-modules: [https://blog.expo.dev/whats-new-in-expo-modules-infrastructure-7a7cdda81ebc](https://blog.expo.dev/whats-new-in-expo-modules-infrastructure-7a7cdda81ebc)

Now I was trying to get it to work for Android with react-native-navigation and i was able to migrate the code to get the app to compile successfully, but with no luck, the navigation is not working.
I think the part where it gets stuck is in `MainActivity.java`

[https://docs.expo.dev/bare/installing-expo-modules/#configuration-for-android](https://docs.expo.dev/bare/installing-expo-modules/#configuration-for-android)

As you can see, the code inside `public class MainActivity extends NavigationActivity` is not working and if I omit the code the app is compiled successfully, but the navigation is not working.

The following code is not working
```
package com.myApp;

import com.reactnativenavigation.NavigationActivity;

import com.facebook.react.ReactActivityDelegate;
import expo.modules.ReactActivityDelegateWrapper;

public class MainActivity extends NavigationActivity {
  @Override
  protected String getMainComponentName() {
    return "MyApp";
  }

  @Override
  protected ReactActivityDelegate createReactActivityDelegate() {
    return new ReactActivityDelegateWrapper(this,
      new ReactActivityDelegate(this, getMainComponentName())
    );
  }
}
```

Some help would be appreciated.

**Comment by kanzitelli** [comment]
Hey @julianklumpers! That looks great, thanks! Did you manage to run it on iOS? Because I didn't try it yet, I have been busy with writing a small library for RNN called [rnn-screens](https://github.com/kanzitelli/rnn-screens), and I am celebrating my bday today, so I will be probably back at the beginning of the next week, and let's integrate it to `rnn-starter`!

**Comment by julianklumpers** [comment]
@kanzitelli 

Congratulations! with your birthday, hope you had a good day.
For IOS i'm working on it as we speak. Will let you know when i have something. nice that we can intergrate it.

**Comment by kanzitelli** [comment]
Hey @julianklumpers! Thank you so much for congrats 🙏 so yeah, the celebration was good and gave me the motivation to work more! So hopefully, I will spend more time on this issue and could help you as well.

**Comment by kanzitelli** [comment]
Hey @julianklumpers! I have created [expo-modules](https://github.com/kanzitelli/rnn-starter/tree/expo-modules) branch where Expo Modules are integrated and the app runs on iOS and Android successfully. If everything works out good, I will add it in the documentation.

**Comment by julianklumpers** [comment]
Hi @kanzitelli. Great to hear it working and will be integrated into this package. Sorry for not responding anymore, was very busy with work.

**Comment by kanzitelli** [comment]
Hey @julianklumpers! That's all right, thank you for the opening this issue and helping out! I will close this for now and add the branch into docs.

**Comment by SudoPlz** [comment]
@kanzitelli @julianklumpers 
it seems like you hooked up the [expo lifecycle events](https://github.com/kanzitelli/rnn-starter/blob/bed89b74065b21bf5682db76cdbbfc96eb6b0c93/android/app/src/main/java/com/rnnstarter/MainApplication.java#L64), but you're not actually using the [expo.modules.ReactNativeHostWrapper](https://github.com/kanzitelli/rnn-starter/blob/bed89b74065b21bf5682db76cdbbfc96eb6b0c93/android/app/src/main/java/com/rnnstarter/MainApplication.java#L5C21-L5C43) anywhere (still [using the react-native-navigation host](https://github.com/kanzitelli/rnn-starter/blob/master/android/app/src/main/java/com/rnnstarter/MainApplication.java#L24))

Is that intentional?
It feels that this (will build but) would actually break expo functionality.
Any idea **what** would break in expo by doing that, I wonder if I can omit it too in my implementation?
