### ISSUE TITLE
how to set headerShown to false on screen

### ISSUE THREAD

**Issue by djdabs** [kanzitelli/rnn-starter#65]
Hello! Thank you for this starter package, great way to get going quick.

I've been struggling to find a way to set headerShown flag on the screens. Tried both in ScreenLayouts and in Screen settings, but neither worked.

Any suggestions on where I need to go to implement this option?

**Comment by kanzitelli** [comment]
hi @djdabs! 

Yes, `headerShown` is not going to work because this starter is using [React Native Navigation](https://github.com/wix/react-native-navigation). If you'd like to hide nav header in RNN, you need to change `topBar.visible` option to `false` for desired screens.
```
Main: {
  component: Main,
  options: {
    topBar: {
      visible: false, // Here
      title: {
        text: 'Main'
      }
    },
  },
},
```

If you want to use React Navigation instead, you need to check out [rn-starter](https://github.com/kanzitelli/rn-starter). The project structure is the same, so won't take a lot of time to get started :)

**Comment by djdabs** [comment]
oh oops! i feel silly for missing that. Thank you for the quick reply!

**Comment by kanzitelli** [comment]
@djdabs no worries! Glad it's helped :)
